SET search_path TO membershipmanager;

INSERT INTO canton(name, abbreviation) VALUES
('Argovie', 'AG'),
('Appenzell Rhodes-Intérieures', 'AI'),
('Appenzell Rhodes-Extérieures', 'AR'),
('Berne', 'BE'),
('Bâle-Campagne', 'BL'),
('Bâle-Ville', 'BS'),
('Fribourg', 'FR'),
('Glaris', 'GL'),
('Grisons', 'GR'),
('Lucerne', 'LU'),
('Nidwald', 'NW'),
('Obwald', 'OW'),
('Saint-Gall', 'SG'),
('Schaffhouse', 'SH'),
('Soleure', 'SO'),
('Schwytz', 'SZ'),
('Thurgovie', 'TG'),
('Tessin', 'TI'),
('Uri', 'UR'),
('Vaud', 'VD'),
('Zoug', 'ZG'),
('Zurich', 'ZH'),
('Genève', 'GE'),
('Valais', 'VS'),
('Jura', 'JU'),
('Neuchâtel', 'NE');
