INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('AG', 'Argovie');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('AI', 'Appenzell Rhodes-Intérieures');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('AR', 'Appenzell Rhodes-Extérieures');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('BE', 'Berne');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('BL', 'Bâle-Campagne');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('BS', 'Bâle-Ville');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('FR', 'Fribourg');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('GL', 'Glaris');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('GR', 'Grisons');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('LU', 'Lucerne');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('NW', 'Nidwald');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('OW', 'Obwald');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('SG', 'Saint-Gall');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('SH', 'Schaffhouse');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('SO', 'Soleure');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('SZ', 'Schwytz');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('TG', 'Thurgovie');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('TI', 'Tessin');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('UR', 'Uri');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('VD', 'Vaud');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('ZG', 'Zoug');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('ZH', 'Zurich');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('GE', 'Genève');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('VS', 'Valais');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('JU', 'Jura');
INSERT INTO membershipmanager.canton (abbreviation, name) VALUES ('NE', 'Neuchâtel');
